# Git config files
- clean:
    - "~/.config/config"
    - "~/.config/.gitconfig_local"
    - "~/.config/ignore"
    - "~/.config/attributes"
    - "~/.config/message"

- link:
    ~/.config/git/config: config/git/gitconfig
    ~/.config/git/.gitconfig_local: config/git/gitconfig_local
    ~/.config/git/ignore: config/git/gitignore
    ~/.config/git/attributes: config/git/gitattributes
    ~/.config/git/message: config/git/gitmessage
