# Git config files
- clean:
    - "~/.config/config"
    - "~/.config/.gitconfig_personal"
    - "~/.config/ignore"
    - "~/.config/attributes"
    - "~/.config/message"

- link:
    # Git config files
    ~/.config/git/config: config/git/gitconfig
    ~/.config/git/ignore: config/git/gitignore
    ~/.config/git/attributes: config/git/gitattributes
    ~/.config/git/message: config/git/gitmessage
    # Git extra config
    ~/.config/git/.gitconfig_personal: config/git/gitconfig_personal
