# Git config files
- clean:
    - "~/.config/config"
    - "~/.config/ignore"
    - "~/.config/attributes"
    - "~/.config/message"

- link:
    # Git config files
    ~/.config/git/config: config/git/gitconfig
    ~/.config/git/ignore: config/git/gitignore
    ~/.config/git/attributes: config/git/gitattributes
    ~/.config/git/message: config/git/gitmessage
# Git extra config
- shell:
    - command: fish './scripts/configure-git.fish'
      description: Installing fish iTerm integration
      stdout: true
      stderr: true
