- shell:
    - brew cleanup
    - [fnm install --lts, install latest LTS node]
    - [fnm alias default "$(node -v), Set this Node version as the default]
    - command: bash -l './packages/npm-global.sh'
      description: Installing npm global packages
      stdout: true
      stderr: true
    - command: bash -l './packages/vscode-extensions.sh'
      description: Installing vscode extensions
      stdout: true
      stderr: true
