- link:
    # omf
    ~/.config/omf: config/omf/
    # wtf
    ~/.config/wtf: config/wtf/
    # fish shell config files
    ~/.config/fish/config.fish:
      path: config/fish/config.fish
    ~/.config/fish/conf.d: config/fish/conf.d/
    ~/.config/fish/functions: config/fish/functions/
    ~/.config/fish/completions: config/fish/completions/
