- defaults:
    link:
      relink: true
      create: true
      force: true
    shell:
      stdout: true
      stderr: true
# - clean:
#     $HOME/.config:
#       recursive: true
#       exclude: "~/.config/fish/.iterm2_shell_integration.fish"
