code --install-extension christian-kohler.path-intellisense
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension mikestead.dotenv
code --install-extension ms-python.python
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension naumovs.color-highlight
code --install-extension skyapps.fish-vscode
code --install-extension vincaslt.highlight-matching-tag
code --install-extension aaron-bond.better-comments
code --install-extension amatiasq.sort-imports
code --install-extension anseki.vscode-color
code --install-extension apollographql.vscode-apollo
code --install-extension burkeholland.simple-react-snippets
code --install-extension byCedric.vscode-expo
code --install-extension christian-kohler.npm-intellisense
code --install-extension codezombiech.gitignore
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dsznajder.es7-react-js-snippets
code --install-extension eg2.vscode-npm-script
code --install-extension esbenp.prettier-vscode
code --install-extension GraphQL.vscode-graphql
code --install-extension kamikillerto.vscode-colorize
code --install-extension mrmlnc.vscode-scss
code --install-extension pflannery.vscode-versionlens
code --install-extension Prisma.prisma
code --install-extension svelte.svelte-vscode
code --install-extension vscode-icons-team.vscode-icons
code --install-extension yzhang.markdown-all-in-one
code --install-extension zhuangtongfa.material-theme
code --install-extension gruntfuggly.todo-tree
code --install-extension streetsidesoftware.code-spell-checker
